### PR TITLE
Added utility to enable SSL.

### PR DESCRIPTION
**Pull request by odkr**
I wrote a simple script based on the instructions I wrote up for the README. I didn't do a whole lot (read: very little) testing, but it works for me; and it's simple enough. That said, I'm not 100% sure how macOS' `security` CLI tool is supposed to work. It doesn't behave as it says in the manual (or as I would read the manual at any rate): I would have thought that its `add-trusted-cert` sub-command should import the given certificate, but it doesn't. If the certificate is imported via `import` first, you can set a trust policy with `add-trusted-cert` though; that is, it works for me on macOS Mojave.

### CODE REVIEW

**Comment by odkr** [comment]
Sure! Just to clarify: By "installing the certificate", do you mean its being added to `radicale.conf` or its being added (and set to trustworthy) in the macOS Keychain?

**Comment by tasn** [comment]
I was talking about the system, but I guess this applies to both. :)
Btw, I just noticed the certificate is not bound to a specific port, could you please also bound it just to the etesync-dav port? Thanks!

**Comment by odkr** [comment]
There are now options to keep the utility from generating a certificate or configuring etesync-dav to use. By default, it will only generate a certificate if there's none (or it's --force'd to) and will only change the configuration if SSL isn't already enabled (or it's --force'd to). It will read the filenames for the certificate and the key from the configuration file. It also won't make the system trust the certificates by default, this must now be requested with --trust-cert, so that users are aware that it's happening. And I made it even more talkative, so it shouldn't leave anybody in the dark as to what is happening ;). 

As for specific port, I'm not sure what you mean, I'm afraid. I thought SSL certificates are per (virtual) host only.

**Comment by tasn** [comment]
Specific port: I think, but I may be wrong, that it's a limitation by CAs, rather than the spec itself, so you can bind a certificate to a specific port. Example from MS: https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-configure-a-port-with-an-ssl-certificate

Not doing this will enable anyone mitm any connection to localhost. There are probably not a crazy amount of such services, so the impact may be insignificant, but it's better to prevent this if possible.

**Comment by odkr** [comment]
So, I did some reading, and from I found, it appears that binding a certificate to ports is non-standard.

[RFC 2818 (sec. 3.1)](https://tools.ietf.org/html/rfc2818#section-3.1) discusses "server identity", *not* 'serv**ice**' identity and states:

> If a subjectAltName extension of type dNSName is present, that MUST
> be used as the identity. Otherwise, the (most specific) Common Name
> field in the Subject field of the certificate MUST be used.

So it would seem that, if anywhere, a port number would have to go in the `commonName` field -- which is deprecated.

The only other way I could think of was using an URI as `subjectAlternativeName`. But no standard-compliant piece of software should look at an URI, of course (as per RFC 2818, sec. 3.1). I still tried with iCal, Firefox, and Chrome for good meassure -- and they all just threw SSL errors at me indeed. It appears that, as far as TLS is concerned, URIs have a very narrowly circumscribed use (cf. [RFC 6125 (sec. 1.7.2)](https://tools.ietf.org/html/rfc6125#section-1.7.2)).

I also couldn't find any discussion of this feature, that is, other than the site you pointed out. OpenSSL makes no mention of it.

**Comment by tasn** [comment]
OK, I guess it is what it is. Thanks for the PR!

I'm a bit wary of the collapseuser and trimsubpath functions. I vaguely remember path pretty print functions exist, but anyhow, I'm not sure if the slightly better UI is worth the added complexity / room for abuse in a security sensitive script.

Btw, I saw you haven't updated the readme and setup.py. Would be great if you could, but if not, that's fine, I'll do it myself at a later stage.

Thanks again!

**Comment by odkr** [comment]
I'm not particular happy with those functions either, but it's just too hard to read the output without some pretty-printing. I tend to ignore `pathlib` because, in my experience, whenever I use it, I just end up with abstractions that do little and just make my code less concise. I just looked at its docs and it does offer a `relative_to` method for paths, but it would require exception handling. And it's the only thing in the standard library I can think of. I'll udpdate the README later, I just didn't want to do it before the script is finished (if binding to ports had worked, this would have required quite some changes).

**Pull request merged**
