### PR TITLE
Readability improvements

### PR DESCRIPTION
**Pull request by stevesbrain**
Slightly updating the macOS instructions section with a few minor readability improvements

### CODE REVIEW

**Comment by tasn** [comment]
Thanks a lot! Could you please put the "or later" in parenthesis? So "macOS Mojave (or later)". I think it'll make things slightly more readable.

Thanks!

**Comment by stevesbrain** [comment]
You're absolutely right - done :)

**Comment by tasn** [comment]
Thanks!

**Comment by porg** [comment]
> "macOS 10.14 Mojave (and later)"

To spare new users some trial and error could you please explicitly (taxatively) state which macOS versions will need what workaround?

Because after 10.14 there are meanwhile "10.15 Catalina" and "10.16 Big Sur".

**Comment by tasn** [comment]
Feel free to open a PR with the change. I wouldn't change the title, but would rather have the first line of the content explain what's up.

**Comment by porg** [comment]
@all Someone who *knows for cetain* the particular etesync/macOS compatibilities/workarounds, could you please edit accordingly?

@tasn I do not have the proper and reliable knowhow, hence cannot make the edit.

**Comment by tasn** [comment]
It affects all of the mac versions starting from Mojave for all I know (as the title says, Mojave or later), it's just a matter of adding the rest of the mac versions at the beginning of the paragraph like I suggested above.

**Pull request merged**
