### PR TITLE
Docker and some minor updates

### PR DESCRIPTION
**Pull request by dan-v**
* Add Docker build and usage instructions
* Update config.py to use environment variables for listen address and port
* Add OSX CalDAV setup instructions
* Update dependencies

### CODE REVIEW

**Comment by tasn** [comment]
Grr, it didn't mark it automatically, but this has been merged in 3aa59fb612f4ba6de627e351fbfda774031e852d

**Comment by tasn** [comment]
Thanks btw, and sorry it took me so long! I was under the impression I replied to this PR before, but I guess I haven't.

Sorry!

**Comment by dan-v** [comment]
Oh nice! No worries - just happened to see the PR was still laying around so figured I'd fix it up. Glad it's already merged in! Docker setup has been working great for me btw :)

**Comment by tasn** [comment]
I just pointed someone to the Docker instructions earlier because he was having issues, so finding it useful already. :)

I guess it can also be useful for windows, will have a note there too.

**Pull request closed without merging**
