### PR TITLE
Extending radicale-3-1-0 support

### PR DESCRIPTION
**Pull request by opiechow**
Description:
    Fixing the issue fixed in 88cb99b also for legacy etesync protocol.

### CODE REVIEW

**Review by tasn — APPROVED** [review]
Thanks a lot!

**Comment by tasn** [comment]
Linting failed. Can you please take a look?

**Comment by opiechow** [comment]
Done, ready to go :)

**Comment by tasn** [comment]
New version released. Thanks a lot!

**Pull request merged**
